# Generated by Django 5.0.7 on 2024-11-18 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreEbayitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gallery_url', models.TextField(max_length=2048)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('item_web_url', models.TextField(max_length=2048)),
                ('availability', models.CharField(max_length=50)),
                ('itemEndDate', models.CharField(max_length=50)),
                ('categoryId', models.CharField(max_length=50)),
                ('categoryIdPath', models.CharField(max_length=100)),
                ('us_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('chest_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_size', models.CharField(blank=True, max_length=50, null=True)),
                ('inseam', models.CharField(blank=True, max_length=50, null=True)),
                ('hip_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_shoulder', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('women_size', models.CharField(blank=True, max_length=50, null=True)),
                ('bottoms_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ring_size', models.CharField(blank=True, max_length=50, null=True)),
                ('necklace_length', models.CharField(blank=True, max_length=50, null=True)),
                ('item_length', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'core_ebayitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreEbayitemSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_url', models.TextField(max_length=2048)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=255)),
                ('item_web_url', models.TextField(max_length=2048)),
                ('availability', models.CharField(max_length=50)),
                ('itemEndDate', models.CharField(max_length=50)),
                ('categoryId', models.CharField(max_length=50)),
                ('categoryIdPath', models.CharField(max_length=100)),
                ('us_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('chest_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_size', models.CharField(blank=True, max_length=50, null=True)),
                ('hip_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('inseam', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_shoulder', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('women_size', models.CharField(blank=True, max_length=50, null=True)),
                ('bottoms_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ring_size', models.CharField(blank=True, max_length=50, null=True)),
                ('necklace_length', models.CharField(blank=True, max_length=50, null=True)),
                ('item_length', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'core_ebayitem_out_of_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=160)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(blank=True, max_length=58)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, null=True)),
                ('is_favorited', models.BooleanField(default=False)),
                ('favorited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_favorited_items',
                'unique_together': {('user', 'item_id')},
            },
        ),
    ]
