# Generated by Django 5.0.7 on 2025-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSizeConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_length_in', models.FloatField()),
                ('us_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('italy_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('uk_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('france_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('japan_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('korea_china_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
