# Generated by Django 5.0.7 on 2025-01-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoesizeconversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoesizeconversion',
            old_name='italy_shoe_size',
            new_name='europe_shoe_size',
        ),
    ]
