# Generated by Django 5.0.7 on 2025-01-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_italy_shoe_size_shoesizeconversion_europe_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesizeconversion',
            name='foot_length_in',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
