# Generated by Django 5.0.7 on 2025-04-10 18:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shoesizeconversion_foot_length_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_picture_upload_path, validators=[core.models.validate_image_size, core.models.validate_image_format]),
        ),
    ]
