# Generated by Django 5.0.7 on 2025-08-18 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailcapture_newsletter_trend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('us_shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('shoe_size_width', models.CharField(blank=True, max_length=50, null=True)),
                ('hat_size', models.CharField(blank=True, max_length=10, null=True)),
                ('chest_size', models.CharField(blank=True, max_length=50, null=True)),
                ('bra_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_size', models.CharField(blank=True, max_length=50, null=True)),
                ('inseam', models.CharField(blank=True, max_length=50, null=True)),
                ('hip_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_shoulder', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_to_hem', models.CharField(blank=True, max_length=50, null=True)),
                ('women_size', models.CharField(blank=True, max_length=50, null=True)),
                ('bottoms_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ring_size', models.CharField(blank=True, max_length=50, null=True)),
                ('necklace_length', models.CharField(blank=True, max_length=50, null=True)),
                ('item_length', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('shoe_size_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shoesizeconversion')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/images/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.marketplaceitem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attribute')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.marketplaceitem')),
            ],
            options={
                'unique_together': {('item', 'attribute')},
            },
        ),
    ]
