# Generated by Django 5.0.7 on 2025-08-26 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attribute_category_marketplaceitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_id', models.CharField(max_length=100)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('detecting', 'Detecting'), ('selecting', 'Selecting'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['batch_id'], name='core_listin_batch_i_f753d3_idx'), models.Index(fields=['user', 'created_at'], name='core_listin_user_id_114b0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TempListingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('original_image_url', models.URLField(max_length=500)),
                ('original_image_key', models.CharField(max_length=255)),
                ('working_image_url', models.URLField(max_length=500)),
                ('working_image_key', models.CharField(max_length=255)),
                ('working_presigned_url', models.URLField(max_length=1000)),
                ('image_metadata', models.JSONField(default=dict)),
                ('detection_results', models.JSONField(blank=True, null=True)),
                ('crop_regions', models.JSONField(default=list)),
                ('selected_indices', models.JSONField(default=list)),
                ('form_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'batch_id'], name='core_templi_session_a842d9_idx'), models.Index(fields=['expires_at'], name='core_templi_expires_52cb41_idx')],
            },
        ),
    ]
